DROP TABLE MEMBER;
DROP TABLE DISCOUNT;
DROP TABLE MENU;
DROP TABLE RES_MENU;
DROP TABLE RESTAURANT;
DROP TABLE LOCATION;
DROP TABLE FOOD;
DROP TABLE RESTAURANT_PICK;
DROP TABLE RESTAURANT_COMMENT;
DROP TABLE PICTURE;

DROP SEQUENCE SEQ_MEMBER;
DROP SEQUENCE SEQ_DISCOUNT;
DROP SEQUENCE SEQ_RESTAURANT_PICK;
DROP SEQUENCE SEQ_RESTAURANT;
DROP SEQUENCE SEQ_LOCATION;    
DROP SEQUENCE SEQ_FOOD;

CREATE SEQUENCE SEQ_PICTURE;
CREATE SEQUENCE SEQ_MENU;
CREATE SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_DISCOUNT;
CREATE SEQUENCE SEQ_RESTAURANT_PICK;
CREATE SEQUENCE SEQ_RESTAURANT;
CREATE SEQUENCE SEQ_LOCATION;    
CREATE SEQUENCE SEQ_FOOD;
CREATE SEQUENCE SEQ_RESTAURANT_COMMENT;

SELECT * FROM RESTAURANT_PICK;
SELECT * FROM RESTAURANT;
SELECT * FROM LOCATION;
SELECT * FROM FOOD;
SELECT * FROM MEMBER;
SELECT * FROM DISCOUNT;
SELECT * FROM MENU;
SELECT * FROM RES_MENU;
SELECT * FROM RESTAURANT_COMMENT;


CREATE TABLE MEMBER(
    MEM_CODE  NUMBER,
    MEM_ID VARCHAR2(20) NOT NULL UNIQUE,
    MEM_NAME VARCHAR2(20) NOT NULL,
    MEM_PWD VARCHAR2(20) NOT NULL,
    MEM_PHONE VARCHAR2(20) NOT NULL,
    MEM_NICKNAME VARCHAR2(20) NOT NULL UNIQUE,
    MEM_GENDER CHAR(3) CHECK(MEM_GENDER IN('남', '여')),
    MEM_AGE NUMBER,
    MEM_EMAIL VARCHAR2(50),
    MEM_ROLE VARCHAR2(10) CHECK(MEM_ROLE IN('사장', '고객', '관리자'))
);

CREATE TABLE DISCOUNT(
    DIS_CODE NUMBER,
    DIS_DESC VARCHAR2(100) NOT NULL,
    DIS_PERIOD VARCHAR2(50) NOT NULL
);

CREATE TABLE RESTAURANT(
    RES_CODE NUMBER,
    RES_NAME VARCHAR2(200) NOT NULL,
    RES_ADDR VARCHAR2(200) NOT NULL,
    RES_PHONE VARCHAR2(200) NOT NULL,
    RES_OPEN_HOUR VARCHAR2(100),  
    RES_CLOSE VARCHAR2(100),  
    RES_DESC VARCHAR2(500),
    LOCAL_CODE NUMBER,
    FOOD_CODE NUMBER,
    MEM_CODE NUMBER
);

CREATE TABLE LOCATION(
    LOCAL_CODE NUMBER,
    LOCAL_NAME VARCHAR2(200) NOT NULL
);

CREATE TABLE FOOD(
    FOOD_CODE NUMBER,
    FOOD_TYPE VARCHAR2(100) NOT NULL
);

CREATE TABLE RESTAURANT_COMMENT(
    COMMENT_CODE NUMBER,
    COMMENT_DETAIL VARCHAR2(200),
    COMMENT_DATE DATE DEFAULT SYSDATE,
    PARENT_COMMENTS VARCHAR2(300),
    MEM_CODE NUMBER,
    REVIEW_CODE NUMBER
);

CREATE TABLE RESERVATION(
    RESER_CODE NUMBER,
    RESER_COM VARCHAR2(200), --complete
    RESER_NO VARCHAR2(200) NOT NULL, --subscriber
    RESER_TIME TIMESTAMP, --SYSTIMESTAMP-INSERT
    MEM_CODE NUMBER,
    RES_CODE NUMBER
);

CREATE TABLE REVIEW(
    REVIEW_CODE NUMBER,
    MEM_ID VARCHAR2(200), -- 일단 만들어놓음
    REVIEW_CONTENT VARCHAR2(200), --리뷰-리뷰내용
    REVIEW_GRADE NUMBER,
    REVIEW_DATE DATE DEFAULT SYSDATE,
    PARANTS_COMMENT_SEQ VARCHAR2(200),
    MEM_CODE NUMBER,
    RES_CODE NUMBER
);

CREATE TABLE PICTURE(
    RES_CODE NUMBER,
    PIC_URL VARCHAR2(300) NOT NULL,
    PIC_NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE RES_MENU(
    RES_CODE NUMBER,
    MENU_CODE NUMBER
);

CREATE TABLE MENU(
    MENU_CODE NUMBER,
    MENU_NAME VARCHAR2(100),
    MENU_PRICE VARCHAR2(50),
    MENU_PICTURE VARCHAR2(200)
);

CREATE TABLE RESTAURANT_PICK(
    RES_CODE NUMBER,
    PICK_TIME DATE DEFAULT SYSDATE,
    MEM_CODE NUMBER 
);

ALTER TABLE RESTAURANT ADD CONSTRAINT RESTAURANT_RES_CODE_PK PRIMARY KEY(RES_CODE);
ALTER TABLE LOCATION ADD CONSTRAINT LOCATION_LOCAL_CODE_PK PRIMARY KEY(LOCAL_CODE);
ALTER TABLE FOOD ADD CONSTRAINT FOOD_FOOD_CODE_PK PRIMARY KEY(FOOD_CODE);
ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_MEM_CODE_PK PRIMARY KEY(MEM_CODE);
ALTER TABLE DISCOUNT ADD CONSTRAINT DISCOUNT_DIS_CODE_PK PRIMARY KEY(DIS_CODE);
ALTER TABLE RESTAURANT_COMMENT ADD CONSTRAINT RESTAURANT_COMMENT_COMMENT_CODE_PK PRIMARY KEY(COMMENT_CODE);
ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_RESER_CODE_PK PRIMARY KEY(RESER_CODE);
ALTER TABLE REVIEW ADD CONSTRAINT REVIEW_REVIEW_CODE_PK PRIMARY KEY(REVIEW_CODE);
ALTER TABLE PICTURE ADD CONSTRAINT PICTURE_RES_CODE_PK PRIMARY KEY (RES_CODE);
ALTER TABLE MENU ADD CONSTRAINT MENU_MENU_CODE_PK PRIMARY KEY (MENU_CODE);


ALTER TABLE RESTAURANT ADD CONSTRAINT RESTAURANT_MEM_CODE_FK FOREIGN KEY(MEM_CODE) REFERENCES MEMBER;
ALTER TABLE RESTAURANT ADD CONSTRAINT RESTAURANT_LOCAL_CODE_FK FOREIGN KEY(LOCAL_CODE) REFERENCES LOCATION;
ALTER TABLE RESTAURANT ADD CONSTRAINT RESTAURANT_FOOD_CODE_FK FOREIGN KEY(FOOD_CODE) REFERENCES FOOD;
ALTER TABLE RESTAURANT_PICK ADD CONSTRAINT RESTAURANT_PICK_RES_CODE_FK FOREIGN KEY(RES_CODE) REFERENCES RESTAURANT(RES_CODE);
ALTER TABLE RESTAURANT_PICK ADD CONSTRAINT RESTAURANT_PICK_MEM_CODE_FK FOREIGN KEY(MEM_CODE) REFERENCES MEMBER(MEM_CODE);
ALTER TABLE RESTAURANT_COMMENT ADD CONSTRAINT RESTAURANT_COMMENT_MEM_CODE_FK FOREIGN KEY(MEM_CODE) REFERENCES MEMBER(MEM_CODE);
ALTER TABLE RESTAURANT_COMMENT ADD CONSTRAINT RESTAURANT_COMMENT_REVIEW_CODE_FK FOREIGN KEY(REVIEW_CODE) REFERENCES REVIEW(REVIEW_CODE);
ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_MEM_CODE_FK FOREIGN KEY(MEM_CODE) REFERENCES MEMBER;
ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_RES_CODE_FK FOREIGN KEY(RES_CODE) REFERENCES RESTAURANT;
ALTER TABLE REVIEW ADD CONSTRAINT REVIEW_MEM_CODE_FK FOREIGN KEY(MEM_CODE) REFERENCES MEMBER;
ALTER TABLE REVIEW ADD CONSTRAINT REVIEW_RES_CODE_FK FOREIGN KEY(RES_CODE) REFERENCES RESTAURANT;
ALTER TABLE RES_MENU ADD CONSTRAINT RES_MENU_RES_CODE_FK FOREIGN KEY(RES_CODE) REFERENCES RESTAURANT;
ALTER TABLE RES_MENU ADD CONSTRAINT MENU_MENU_CODE_FK FOREIGN KEY(MENU_CODE) REFERENCES MENU;






INSERT INTO MENU VALUES(1, '맛있는음식', '10,000원', '사진');
INSERT INTO MENU VALUES(2, '맛없는음식', '20,000원', '사진2');
INSERT INTO MENU VALUES(3, '맛있던음식', '10,002원', '사진2');

INSERT INTO MEMBER VALUES(SEQ_MEM.NEXTVAL, 'JS', '박진실', '1111', '1111', '1111', '여', '27', '1111', '고객');
INSERT INTO MEMBER VALUES(SEQ_MEM.NEXTVAL, 'SM', '신수민', '2222', '2222', '2222', '여', '27', '2222', '고객');
INSERT INTO MEMBER VALUES(SEQ_MEM.NEXTVAL, 'KM', '김경미', '3333', '3333', '3333', '여', '27', '3333', '사장');
INSERT INTO MEMBER VALUES(SEQ_MEM.NEXTVAL, 'JH', '최준혁', '4444', '4444', '4444', '남', '27', '4444', '관리자');
INSERT INTO MEMBER VALUES(SEQ_MEM.NEXTVAL, 'JY', '박주영', '5555', '5555', '5555', '남', '27', '5555', '관리자');
INSERT INTO DISCOUNT VALUES(SEQ_DISCOUNT.NEXTVAL, '80퍼센트 할인', '8.18~8.23');
INSERT INTO DISCOUNT VALUES(SEQ_DISCOUNT.NEXTVAL, '70퍼센트 할인', '8.20~8.30');
INSERT INTO RESTAURANT(RES_CODE, RES_NAME, RES_ADDR, RES_PHONE) VALUES(SEQ_RESTAURANT.NEXTVAL, '김밥천국', '서울 강남구', '02-111-1111');
INSERT INTO RESTAURANT(RES_CODE, RES_NAME, RES_ADDR, RES_PHONE) VALUES(SEQ_RESTAURANT.NEXTVAL, '나이스샤워', '서울 강남구', '02-222-2222');
INSERT INTO RESTAURANT(RES_CODE, RES_NAME, RES_ADDR, RES_PHONE) VALUES(SEQ_RESTAURANT.NEXTVAL, '김남완초밥', '서울 강남구', '02-333-3333');
INSERT INTO LOCATION(LOCAL_CODE, LOCAL_NAME) VALUES(SEQ_LOCATION.NEXTVAL, '서울');
INSERT INTO LOCATION(LOCAL_CODE, LOCAL_NAME) VALUES(SEQ_LOCATION.NEXTVAL, '경기');
INSERT INTO LOCATION(LOCAL_CODE, LOCAL_NAME) VALUES(SEQ_LOCATION.NEXTVAL, '인천');
INSERT INTO FOOD(FOOD_CODE, FOOD_TYPE) VALUES(SEQ_FOOD.NEXTVAL, '한식');
INSERT INTO FOOD(FOOD_CODE, FOOD_TYPE) VALUES(SEQ_FOOD.NEXTVAL, '양식');
INSERT INTO FOOD(FOOD_CODE, FOOD_TYPE) VALUES(SEQ_FOOD.NEXTVAL, '일식');
INSERT INTO FOOD(FOOD_CODE, FOOD_TYPE) VALUES(SEQ_FOOD.NEXTVAL, '중식');