
--예약
CREATE TABLE RESERVATION(
    RESER_CODE NUMBER,
    RESER_COM VARCHAR2(200), --complete
    RESER_NO VARCHAR2(200) NOT NULL, --subscriber
    RESER_TIME TIMESTAMP, --SYSTIMESTAMP-INSERT
    MEM_CODE NUMBER,
    RES_CODE NUMBER
);
--리뷰
CREATE TABLE REVIEW(
    REVIEW_CODE NUMBER,
    MEM_ID VARCHAR2(200), -- 일단 만들어놓음
    REVIEW_CONTENT VARCHAR2(200), --리뷰-리뷰내용
    REVIEW_GRADE NUMBER,
    REVIEW_DATE DATE DEFAULT SYSDATE,
    PARANTS_COMMENT_SEQ VARCHAR2(200),
    MEM_CODE NUMBER,
    RES_CODE NUMBER
);

--예약
ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_RESER_CODE_PK PRIMARY KEY(RESER_CODE);

--리뷰
ALTER TABLE REVIEW ADD CONSTRAINT REVIEW_REVIEW_CODE_PK PRIMARY KEY(REVIEW_CODE);

--예약
ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_MEM_CODE_FK FOREIGN KEY(MEM_CODE) REFERENCES MEMBER;
ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_RES_CODE_FK FOREIGN KEY(RES_CODE) REFERENCES RESTAURANT;

--리뷰
ALTER TABLE REVIEW ADD CONSTRAINT REVIEW_MEM_CODE_FK FOREIGN KEY(MEM_CODE) REFERENCES MEMBER;
ALTER TABLE REVIEW ADD CONSTRAINT REVIEW_RES_CODE_FK FOREIGN KEY(RES_CODE) REFERENCES RESTAURANT;

--예약
CREATE SEQUENCE SEQ_RESERVATION;
--리뷰
CREATE SEQUENCE SEQ_REVIEW;

select * from reservation;
select * from review;



