--예약
CREATE TABLE RESERVATION(
    RES_NO NUMBER,
    RES_COM VARCHAR2(200), --complete
    SUB_NO VARCHAR2(200) NOT NULL, --subscriber
    RES_TIME TIMESTAMP, --SYSTIMESTAMP-INSERT
    MEMBER_NO NUMBER,
    RESTAURANT_NO NUMBER
);
--리뷰
CREATE TABLE REVIEW(
    REVIEW_NO NUMBER,
    ID VARCHAR2(200),
    REVIEW_CONTENT VARCHAR2(200), --리뷰-리뷰내용
    GRADE NUMBER,
    REVIEW_DATE DATE DEFAULT SYSDATE,
    PARANTS_COMMENT_SEQ VARCHAR2(200),
    MEMBER_NO NUMBER,
    RESTAURANT_NO NUMBER
);

--예약
ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_RES_NO_PK PRIMARY KEY(RES_NO);
--리뷰
ALTER TABLE REVIEW ADD CONSTRAINT REVIEW_REVIEW_NO_PK PRIMARY KEY(REVIEW_NO);

--예약
ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_MEMBER_NO_FK FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER;
ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_RESTAURANT_NO_FK FOREIGN KEY(RESTAURANT_NO) REFERENCES RESTAURANT;
--리뷰
ALTER TABLE REVIEW ADD CONSTRAINT REVIEW_MEMBER_NO_FK FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER;
ALTER TABLE REVIEW ADD CONSTRAINT REVIEW_RESTAURANT_NO_FK FOREIGN KEY(RESTAURANT_NO) REFERENCES RESTAURANT;

--예약
CREATE SEQUENCE SEQ_RESERVATION;
--리뷰
CREATE SEQUENCE SEQ_REVIEW;





