
  
 --1번
 SELECT STUDENT_NO "학번", STUDENT_NAME "이름", ENTRANCE_DATE "입학년도"
 FROM TB_STUDENT
 WHERE DEPARTMENT_NO = '002'
 ORDER BY ENTRANCE_DATE;
 
 --2번
 SELECT PROFESSOR_NAME, PROFESSOR_SSN
 FROM TB_PROFESSOR
 WHERE LENGTH(PROFESSOR_NAME) != 3;
 
  select * from TB_CLASS;
  select * from TB_CLASS_PROFESSOR;
  select * from TB_DEPARTMENT;
  select * from TB_GRADE;
  select * from TB_PROFESSOR;
  select * from TB_STUDENT;
  
 --3번
 SELECT PROFESSOR_NAME "교수이름", TRUNC(MONTHS_BETWEEN(TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6), 'YYMMDD'), SYSDATE) / 12) "나이"
 FROM TB_PROFESSOR
 WHERE PROFESSOR_SSN NOT LIKE '0%' AND SUBSTR(PROFESSOR_SSN,8,1) IN (1)
 ORDER BY PROFESSOR_SSN;
 
 --4번
 SELECT SUBSTR(PROFESSOR_NAME, 2, 3) "이름"
 FROM TB_PROFESSOR;
 
 --5번 -- 모르겠음
 SELECT STUDENT_NO, STUDENT_NAME
 FROM TB_STUDENT
 WHERE TRUNC(MONTH_BETWEEN(TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6), 'YYMMDD'), ENTRANCE_DATE) /12) ;
 
 --6번
 SELECT TO_CHAR(TO_DATE('20201225', 'YYYYMMDD'), 'DAY') "크리스마스_요일"
 FROM DUAL;
 
 --7번
 SELECT TO_CHAR(TO_DATE('99/10/11', 'YY/MM/DD'), 'YYYY"년" MM"월" DD"일"'),
             TO_CHAR(TO_DATE('49/10/11', 'YY/MM/DD'), 'YYYY"년" MM"월" DD"일"'),
              TO_CHAR(TO_DATE('99/10/11', 'RR/MM/DD'), 'RRRR"년" MM"월" DD"일"'),
                 TO_CHAR(TO_DATE('49/10/11', 'RR/MM/DD'), 'RRRR"년" MM"월" DD"일"')
 FROM DUAL;
 
 --8번
 SELECT STUDENT_NO, STUDENT_NAME
 FROM TB_STUDENT
 WHERE STUDENT_NO NOT LIKE 'A%';
 
 --9번
 SELECT ROUND(AVG(POINT), 1) "평점"
 FROM TB_GRADE
 WHERE STUDENT_NO = 'A517178';
 
 --10번
 

 
 
 
 
 
 
 
 
 
 
 