--1번
 SELECT STUDENT_NAME 학생이름, STUDENT_ADDRESS 주소지
 FROM TB_STUDENT
 ORDER BY STUDENT_NAME;
 
 --2번
 SELECT STUDENT_NAME, STUDENT_SSN
 FROM TB_STUDENT
 WHERE ABSENCE_YN = 'Y'
 ORDER BY STUDENT_SSN DESC;
 
 --3번
  SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번, STUDENT_ADDRESS 거주지주소
  FROM TB_STUDENT
  WHERE (STUDENT_ADDRESS LIKE '강원%' OR STUDENT_ADDRESS LIKE '경기%')
  AND SUBSTR(STUDENT_NO, 1, 1) = '9'
  ORDER BY STUDENT_NAME;
  
 --4번
  SELECT PROFESSOR_NAME, PROFESSOR_SSN
  FROM TB_PROFESSOR
  WHERE DEPARTMENT_NO = '005'
  ORDER BY PROFESSOR_SSN;
  
 --5번
 SELECT STUDENT_NO, POINT
 FROM TB_GRADE 
 WHERE TERM_NO = 200402
 AND CLASS_NO = 'C3118100'
 ORDER BY POINT DESC ,STUDENT_NO;
 
 