--1. 춘 기술대학교의 학과 이름과 계열을 표시하시오. 단, 출력 헤더는 "학과 명", "계열" 으로 표시하도록 한다.
 SELECT DEPARTMENT_NAME "학과 명", CATEGORY "계열"
 FROM TB_DEPARTMENT;

--2. 학과의 학과 정원을 다음과 같은 형태로 화면에 출력한다.
 SELECT DEPARTMENT_NAME || '의 정원은' || CAPACITY || '명 입니다.'
 FROM TB_DEPARTMENT;
 
  select * from TB_CLASS;
  select * from TB_CLASS_PROFESSOR;
  select * from TB_DEPARTMENT;
  select * from TB_GRADE;
  select * from TB_PROFESSOR;
  select * from TB_STUDENT;
 
 --3. "국어국문학과"에 다니는 여학생 중 현재 휴학중인 여학생을 찾아달라는 요청이 들어왔다. 누구인가? 
-- (국문학과의 '학과코드'는 학과 테이블(TB_DEPARTMENT)을 조회해서 찾아 내도록 하자)
 SELECT STUDENT_NAME
 FROM TB_STUDENT
 WHERE DEPARTMENT_NO = '001' AND STUDENT_SSN LIKE '_______2%' AND ABSENCE_YN = 'Y';
 
 -- 4. "국어국문학과"에 다니는 여학생
 SELECT STUDENT_NAME
 FROM TB_STUDENT
 WHERE STUDENT_NO IN('A513079', 'A513090', 'A513091', 'A513110', 'A513119');
 
-- 5번
 SELECT DEPARTMENT_NAME, CATEGORY
 FROM TB_DEPARTMENT
 WHERE CAPACITY BETWEEN 20 AND 30;
 
-- 6번
 SELECT PROFESSOR_NAME
 FROM TB_PROFESSOR
 WHERE DEPARTMENT_NO IS NULL;
 
-- 7번
 SELECT *
 FROM TB_STUDENT
 WHERE DEPARTMENT_NO IS NULL;
 
-- 8번
 SELECT CLASS_NO
 FROM TB_CLASS
 WHERE PREATTENDING_CLASS_NO IS NOT NULL;
 
-- 9번
 SELECT DISTINCT CATEGORY
 FROM TB_DEPARTMENT;
 
-- 10번
 SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
 FROM TB_STUDENT
 WHERE ENTRANCE_DATE LIKE '%02%' AND STUDENT_ADDRESS LIKE '%전주%' AND ABSENCE_YN = 'N';







 